# ==========================================================================================
# AUTHOR: Andrew Harris
#	  Schatz Energy Research Center
#	  Humboldt State University
# ==========================================================================================
# VERSION:
#   2018-05-25 Initial Development
# ==========================================================================================
# This defines an object class to store the multiple values that will be generated by these
# modules - the 100 year emissions timeline, the percentage mass loss, and the remaining moisture
# ==========================================================================================
setClass("module.output",
         slots=c(
           emissions.timeline = "data.frame",
           mass.loss = "numeric",
           remaining.moisture = "numeric"
         )
)